### ISSUE TITLE
inferator vs ansible playbooks / tower

### ISSUE THREAD

**Issue by durandom** [tchughesiv/inferator#17]
Hey @tchughesiv , 
do you have some insights on what inferator solves vs ansible playbooks + ansible tower?

E.g. "prom alert" -> "execute playbook"

**Comment by tchughesiv** [comment]
hey @durandom,

Inferator is really just meant to be an easy solution for simple problems. We’re still in prototype phase for this operator, but here are some thoughts on your question.

With Ansible, you can build more comprehensive automation but sometimes that's overkill for watching something and flipping a switch. Administrators and SREs will wish there was an operator for this, or that, but creating one with Go (or even Ansible) is too much of an investment. Here, we hope to provide a simple and declarative yaml syntax to create an operator that plugs any identified gap.

Easy / quick / simple... You need more? Go to Ansible!

**Comment by durandom** [comment]
thanks for the explanation. makes sense....
